name: upence
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.0

  # Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.4
  path: ^1.9.0

  # Permissions
  permission_handler: ^11.3.0

  # SMS
  flutter_sms_inbox: ^1.0.0

  # Notifications
  flutter_local_notifications: ^17.2.1

  # Platform Channels
  flutter_background_service: ^5.0.10

  # UI
  flutter_svg: ^2.0.10+1
  material_color_utilities: ^0.11.1
  flutter_iconpicker: ^4.0.3
  flutter_colorpicker: ^1.1.0

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  drift_dev: ^2.14.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
